#! /usr/bin/guile -s
!#

;; Bootstrap
(add-to-load-path "./module")
(use-modules (spec suite)
             (ice-9 getopt-long))

(define option-spec
       '((version (single-char #\v) (value #f))
         (help    (single-char #\h) (value #f))))

(define options (getopt-long (command-line) option-spec))

(define (run-specs)
  (spec-run (map load (option-ref options '() #f))))

(define (main)
  (define (help-wanted?)
    (option-ref options 'help #f))
  (define (version-wanted?)
    (option-ref options 'version #f))
  (cond ((help-wanted?)
         (display "guile-spec [files]\n")
         (exit))
        ((version-wanted?)
         (display "guile-spec version 0.1")
         (exit)))
 (run-specs))

(main)
